[workspace]
resolver = "2"
members = ["crates/core", "crates/ui", "crates/config", "crates/keymap", "crates/syntax", "crates/fs", "crates/fuzzy", "crates/commands", "crates/lsp", "crates/app"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Francisco López"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/1franky/tcode"

[workspace.dependencies]
tcode-core = { path = "crates/core" }
tcode-ui = { path = "crates/ui" }
tcode-config = { path = "crates/config" }
tcode-keymap = { path = "crates/keymap" }
tcode-syntax = { path = "crates/syntax" }
tcode-fs = { path = "crates/fs" }
tcode-fuzzy = { path = "crates/fuzzy" }
tcode-commands = { path = "crates/commands" }
tcode-lsp = { path = "crates/lsp" }
ropey = "1.6"
crossterm = "0.28"
ratatui = "0.29"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
dirs = "5"
tokio = "1"
tokio-stream = "0.1"
lsp-types = "0.97"
tree-sitter = "0.27"
tree-sitter-highlight = "0.27"
tree-sitter-rust = "0.24"
tree-sitter-python = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-go = "0.25"
tree-sitter-md = "0.5"
tempfile = "3"
regex = "1"
pulldown-cmark = "0.12"

[profile.release]
lto = true
codegen-units = 1
strip = true
