[package]
name = "tcode"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "tcode: editor TUI portable con atajos estilo VSCode."

[[bin]]
name = "tcode"
path = "src/main.rs"

[dependencies]
tcode-core.workspace = true
tcode-ui.workspace = true
tcode-config.workspace = true
tcode-keymap.workspace = true
tcode-syntax.workspace = true
tcode-fs.workspace = true
tcode-commands.workspace = true
tcode-lsp.workspace = true
ratatui.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }
anyhow.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "io-util", "sync"] }
tokio-stream.workspace = true
