[package]
name = "tcode"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "tcode: editor TUI portable con atajos estilo VSCode."

[[bin]]
name = "tcode"
path = "src/main.rs"

[dependencies]
tcode-core.workspace = true
tcode-ui.workspace = true
tcode-config.workspace = true
tcode-keymap.workspace = true
tcode-syntax.workspace = true
tcode-fs.workspace = true
ratatui.workspace = true
crossterm.workspace = true
anyhow.workspace = true
