[package]
name = "tcode-fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Explorador de archivos de tcode: árbol de directorios navegable, buscador difuso."

[dependencies]
anyhow.workspace = true
tcode-fuzzy.workspace = true
tcode-core.workspace = true
ignore.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
